/**
 * Authoritative itemId → shop/placement kind for server-side validation.
 * Keep aligned with `frontend/src/game/assets/catalog.js` and `SHOP_PRICE_BY_ITEM_ID`.
 */
const ITEM_ID_TO_KIND = {
  forest_tree_a: "tree",
  forest_tree_b: "tree",
  forest_tree_tall_a: "tree",
  forest_tree_fat: "tree",
  forest_tree_detailed: "tree",
  forest_flower_a: "flower",
  forest_flower_b: "flower",
  forest_flower_purple_a: "flower",
  forest_flower_red_c: "flower",
  glacier_flower_purple: "flower",
  glacier_tree_christmas: "decor",
  glacier_decor_present_a: "decor",
  glacier_decor_wreath: "decor",
  glacier_decor_snowman: "decor",
  forest_pet_dog: "decor",
  forest_pet_fox: "decor",
  forest_pet_cow: "decor",
  forest_pet_bunny: "decor",
  forest_pet_beaver: "decor",
  forest_pet_elephant: "decor",
  forest_pet_moose: "decor",
  forest_pet_tiger: "decor",
  glacier_pet_penguin: "decor",
  glacier_pet_polar_bear: "decor",
  my_scene_seedling_sign: "decor",
  my_scene_fantasy_lantern: "decor",
  my_scene_fantasy_fountain: "decor",
  my_scene_fantasy_hedge: "decor",
  my_scene_fantasy_pillar: "decor",
  my_scene_fantasy_road_bend: "decor",
  my_scene_recycle_bin: "decor",
  my_scene_grave_altar: "decor",
  my_scene_grave_bench: "decor",
  my_scene_grave_coffin: "decor",
  my_scene_grave_crypt: "decor",
  my_scene_grave_fire_basket: "decor",
  my_scene_holiday_lantern: "decor",
  my_scene_holiday_floor_stone: "decor",
  my_scene_holiday_gingerbread: "decor",
  my_scene_holiday_wreath_wall: "decor",
  my_scene_house_suburban_a: "decor",
  my_scene_house_suburban_b: "decor",
  my_scene_house_suburban_c: "decor",
  my_scene_house_suburban_d: "decor",
  my_scene_house_suburban_e: "decor",
  my_scene_house_suburban_f: "decor",
  my_scene_house_suburban_g: "decor",
  my_scene_house_suburban_h: "decor",
  my_scene_house_suburban_i: "decor",
  my_scene_house_suburban_j: "decor",
  my_scene_house_suburban_k: "decor",
  my_scene_house_suburban_l: "decor",
  my_scene_house_suburban_m: "decor",
  my_scene_house_suburban_n: "decor",
  my_scene_house_suburban_o: "decor",
  forest_grass_a: "ground",
  forest_grass_b: "ground",
  city_pave_a: "ground",
  city_pave_b: "ground",
  city_tree_a: "tree",
  city_tree_b: "tree",
  city_flower_a: "flower",
  city_flower_b: "flower",
  my_scene_cabin: "decor",
};

function getPlacementKindForItemId(itemId) {
  const id = itemId ? String(itemId).trim() : "";
  if (!id) return null;
  return ITEM_ID_TO_KIND[id] || null;
}

module.exports = { ITEM_ID_TO_KIND, getPlacementKindForItemId };
